### ISSUE TITLE
Write JSON output file per ROS package

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#352]
Add the option to the JSON reporting plugin to write a single output file per package. This would be used when scanning a workspace (with the `-ws` flag). The new plugin can be named `json_reporting_plugin` and make it capable of both writing and printing. The `print_json_reporting_plugin` can be marked as deprecated. The different modes (writing and printing) can be controlled in `config.yaml` with something like

```yaml
json_reporting_plugin:
  terminal: true|false
  files: true|false
```
