### ISSUE TITLE
Fix publishing documentation.

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick#515]
When we make a new release we are getting failures on the publish workflow related to permissions. This SO answer says we can fix it by giving explicit write permissions in the workflow file.

https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot

```yaml
jobs:
  job-name:
    permissions:
      contents: write
```
